import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./component/authContext";
import { CustomizeProvider } from './component/customizeContext';

const instrument = Instrument_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Link Sharing App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={instrument.className}>
        <CustomizeProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </CustomizeProvider>

      </body>
    </html>
  );
}
